Add proof endpoints for withdrawal process
worldcoin/hubble-commander pull request #508
Opened 2021-12-30 12:27 UTC by duckception

2022-01-05 13:19 UTC, b-tarczynski requested changes
Maybe add tests querying for batch that has different batchType than MassMigration

2022-01-05 13:19 UTC, b-tarczynski commented on api/get_mass_migration_commitment_proof.go
> +	commitment, err := a.storage.GetTxCommitment(&commitmentID)
We can use `commitment := commitments[commitmentID.IndexInBatch].(*models.TxCommitment)` instead of that query.

2022-01-05 13:19 UTC, b-tarczynski commented on api/get_mass_migration_commitment_proof.go
> +	batch, err := a.storage.GetBatch(batchID)
We can check after that if type is `batchtype.MassMigration`, otherwise we can return correct error

2022-01-05 13:19 UTC, b-tarczynski commented on api/get_mass_migration_commitment_proof_test.go
> +	witnessIndex := 0
We can pass `witnessIndex` as function argument instead.

2022-01-05 13:50 UTC, duckception commented on api/get_withdraw_proof.go
> +	_, err := a.storage.GetBatch(batchID)
This check was added to verify that the batch exists and stop using unnecessary processing power if the batch didn't exist. But you're right, I missed the case if the batch is of wrong type. Still, I believe that verifying the batch type immediately after this call is faster than calling the `GetMassMigrationsByCommitmentID` for a wrong batch type (`Get` vs `Find`). What do you think?

2022-01-05 14:11 UTC, b-tarczynski commented on api/get_withdraw_proof.go
> +	_, err := a.storage.GetBatch(batchID)
Yes, it's probably faster, so we can leave that check with additional batch type check.

2022-01-10 12:20 UTC, b-tarczynski approved these changes

2022-01-10 12:21 UTC, merged