Add v0.5.0-rc3 changelist
worldcoin/hubble-commander pull request #562
Opened 2022-02-02 09:50 UTC by duckception

2022-02-02 10:11 UTC, msieczko requested changes

2022-02-02 10:31 UTC, msieczko commented on docs/v0.5.0-rc3-changelist.md
> +- `Batch`
Refer to API methods that use these types

2022-02-03 10:24 UTC, duckception commented on docs/v0.5.0-rc3-changelist.md
> +            - `SubmissionBlock` field is now optional.
Resolved in #565.

2022-02-04 10:07 UTC, msieczko commented
The changing was used in release https://github.com/worldcoin/hubble-commander/releases/tag/v0.5.0.

2022-02-04 10:07 UTC, closed without merging